#!/usr/bin/env ruby

EXE_FLAG = ARGV[0];
BINARY="node-template";
RUNTIME="node-template-runtime";

if (EXE_FLAG == "check")
  system("cargo check -p #{RUNTIME}")

elsif (EXE_FLAG == "build")
  system("cargo build --release")

elsif (EXE_FLAG == "clean")
  system("./target/release/#{BINARY} purge-chain --dev && ./target/release/#{BINARY} --dev");

else
  system("./target/release/#{BINARY} --dev");

end
